---
language: python
python: "2.7"

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - 'printf ''[defaults]\nroles_path=../'' >ansible.cfg'

env:
  - ANSIBLE_HOST_KEY_CHECKING=False WAIT_FOR_ERLANG=60

script:
  - ansible-playbook tests/test.yml -v -i tests/inventory
  - 'curl -XPOST http://localhost:8098/types/counters/buckets/mybucket/datatypes/mycounter  -H "Content-Type: application/json"  -d ''{"increment": 0}'''
  - curl http://localhost:8098/types/counters/buckets/mybucket/datatypes/mycounter

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: ZtgcjTxhTxrzWW6MIHLRtucW/BMm42RKS3nGRtSfgER9rx7oJ0Y9gOYkh1FM0GsM7Z11Q/iDhWs/8WTccAV0PrMZ6KHaq54wGmfYyqwPM4YreUwQ87PnOW4wZbl0TJTeWutasEwZvnVJ8VEyyQcS2PHt0zlsENn0XWvobvaZ+FM=
