---
- name: Include RHEL vars
  include_vars: RedHat.yml
  tags: RedHat

- name: "Install Java & libselinux-python"
  yum: "name={{ item }} state=present"
  tags: RedHat
  with_items:
    - java-1.7.0-openjdk
    - libselinux-python

- name: Check if Riak is installed
  stat: path=/etc/riak/riak.conf
  register: dist

- name: Set up packagecloud install script
  template: src=packagecloud_rpm.sh.j2 dest=/tmp/packagecloud_rpm.sh group=root mode=0755

- name: Install package cloud repo if Riak is not already installed
  command: '/tmp/packagecloud_rpm.sh'
  tags: RedHat
  when: not dist.stat.exists

- name: Install Riak for RedHat
  yum: "name={{ riak_package }} state=present"
  tags: RedHat
